export enum LPHStaffRole {
    ADMIN = 'admin',
    DOCTOR = 'doctor',
    NURSE = 'nurse',
    PHARMACIST = 'pharmacist',
    RECEPTIONIST = 'receptionist',
    ACCOUNTANT = 'accountant',
    MANAGER = 'manager',
    LAB = 'Lab',
    RADIOLOGIST = 'radiologist',
    XRAY_TECHNICIAN = 'xray_technician',
    SURGEON = 'surgeon',
    CLINICAL_OFFICER = 'clinical_officer',
    FINANCE = 'Finance',
    BACKSTORE = 'Backstore',
    DENTAL = 'Dental',
    MARTENITY = 'Martenity',
    OPD = 'OPD',
    PHARMACY2 = 'Pharmacy2',
  }
  